### ISSUE TITLE
Error running script

### ISSUE THREAD

**Issue by Sh4ftMaster** [dcampillo/arr-unmonitor#1]
Hi, I can't get the script to test in Radarr. I'm running Windows 10 and python 3.11.

I've pasted in the radarr api key, and for the host I've entered Radarr's IP as:

192.168.0.xx:xx - Which gives error 9009

http://192.168.0.xx:xx/ - Which returns error 1

Apologies if I'm missing something obvious.

**Comment by dcampillo** [comment]
One of the potential issue is related to a missing dependency on the "requests" library. This dependencies was not describe in the documentation:
- Open a command line and install the dependencies by executing `pip install -r requirements.txt`

**Comment by Sh4ftMaster** [comment]
Ah, I should've noticed that. After installing dependencies I've gotten it to test, however the script doesn't seem to be working. I've downloaded a handful of movies and all of them upon completion still show as monitored.

**Comment by dcampillo** [comment]
But the script passes the test?

**Comment by Sh4ftMaster** [comment]
Yes. The test button when adding the script gives a tick and allows me to save. But when downloading a movie it's still monitored.

**Comment by dcampillo** [comment]
Well can you look through the Radarr logs and share the corresponding
message ?

Thanks

**Comment by Sh4ftMaster** [comment]
[radarr.txt](https://github.com/dcampillo/arr-unmonitor/files/9904244/radarr.txt)
 
Relevant information at the very bottom. No connection adaptors found.

Edit: Also I'm using a vpn if that makes a difference

**Comment by dcampillo** [comment]
The issue have been resolve in release v0.7.
No need for any requirements.txt, as all external dependencies have been removed
Documentation has been changed too. The host parameter needs to be a the hostname in the form of "https://[hostname]"

**Comment by Sh4ftMaster** [comment]
Thank you for taking the time to fix this. I'm terribly sorry but I'm now getting a different error. Is this because I still have the dependencies installed? If so how would I go about removing them.
[radarr.txt](https://github.com/dcampillo/arr-unmonitor/files/9932430/radarr.txt)

**Comment by dcampillo** [comment]
Please try version v0.8.1. I have added some more error handling, which should help you find where is your issue.

The "requests" dependency isn't the culprit, but you can remove it with `pip uninstall requests`

**Comment by Sh4ftMaster** [comment]
[radarr.txt](https://github.com/dcampillo/arr-unmonitor/files/9940922/radarr.txt)

**Comment by dcampillo** [comment]
Did you specify the port of the host? Default should be 7878 with Radarr.

**Comment by Sh4ftMaster** [comment]
Yes. Here's the script.
[radarr-unmonitor.zip](https://github.com/dcampillo/arr-unmonitor/files/9944668/radarr-unmonitor.zip)

**Comment by dcampillo** [comment]
Can you try to remive the trailing '/' in the host.

**Comment by Sh4ftMaster** [comment]
That did it. All seems to be working, thanks again.

**Comment by dcampillo** [comment]
Glad to hear it!

**Comment by dcampillo** [comment]
The latest version v0.9b has new settings to simplify the setup. I will update the documentation.
